# define stages
stages:
  - test:basis
  - test:run

########################################################################################################################
# test stages

# run composer and load (dev) dependencies
test:composer:
  stage: test:basis
  tags:
    - docker
  image: ${GLOBAL_DOCKER_COMPOSER_IMAGE}
  script:
    - composer validate --no-check-all --no-check-publish
    - composer install --no-interaction
  artifacts:
    paths:
      - vendor/
    expire_in: 1 hour

# run unit tests
test:phpunit:7.4:
  stage: test:run
  tags:
    - docker
  dependencies:
    - test:composer
  image: finalgene/php-cli:7.4
  variables:
    XDEBUG_ENABLE: 1
  script:
    # lint php files
    - find src/ -name '*.php' -print0 | xargs -0 php -l
    - find tests/ -name '*.php' -print0 | xargs -0 php -l
    # run unit tests
    - vendor/bin/phpunit --coverage-clover .report/phpunit.coverage.xml --log-junit .report/phpunit.xml --coverage-text --colors=never
  artifacts:
    paths:
      - tests/.report/
    expire_in: 1 hour
